# Generated by Django 4.0.6 on 2022-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('hotel_image', models.CharField(max_length=150)),
                ('hotel_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
