# Generated by Django 4.0.6 on 2022-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_details',
            name='hotel_type',
            field=models.CharField(default='hotel', max_length=50),
        ),
    ]
