# Generated by Django 4.0.6 on 2022-08-18 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_resultsnotfound'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('startday', models.DateField()),
                ('endday', models.DateField()),
                ('price', models.IntegerField()),
                ('hotelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hotel_details')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
